//! ZeroClaw API Kernel Traits
//!
//! This crate defines the microkernel interfaces for the ZeroClaw AI Agent Framework.
//! In accordance with the project philosophy, these traits enforce strict type definitions
//! and explicitly separate execution results from security boundaries.

use ed25519_dalek::{Signature, Signer, SigningKey};
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

/// The context in which a tool executes, containing security parameters.
#[derive(Debug, Clone)]
pub struct ToolContext {
    /// The persistent Ed25519 private key bytes used for cryptographic receipts.
    pub identity_key_bytes: Vec<u8>,
}

/// A cryptographic receipt ensuring an immutable audit log of tool execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CryptographicReceipt {
    /// The Ed25519 signature of the execution (hex encoded).
    pub signature: String,
    /// The timestamp of execution.
    pub timestamp: u64,
}

impl CryptographicReceipt {
    /// Generates a receipt by signing the tool name, args, result, and timestamp with the Ed25519 key.
    pub fn generate(
        identity_key_bytes: &[u8],
        tool_name: &str,
        args: &serde_json::Value,
        success: bool,
        output: &str,
        error: Option<&String>,
    ) -> Self {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // Construct the payload to sign
        let mut payload = Vec::new();
        payload.extend_from_slice(tool_name.as_bytes());
        payload.extend_from_slice(args.to_string().as_bytes());
        payload.push(success as u8);
        payload.extend_from_slice(output.as_bytes());
        if let Some(err) = error {
            payload.extend_from_slice(err.as_bytes());
        }
        payload.extend_from_slice(&timestamp.to_be_bytes());

        // Sign the payload
        let secret_key: [u8; 32] = identity_key_bytes
            .try_into()
            .expect("Identity key must be exactly 32 bytes");
        let signing_key = SigningKey::from_bytes(&secret_key);
        let sig: Signature = signing_key.sign(&payload);

        let signature = hex::encode(sig.to_bytes());

        Self {
            signature,
            timestamp,
        }
    }
}

/// Represents the execution result of a tool.
///
/// Ensures explicit reporting back to the LLM (and audit log)
/// about whether an action succeeded or failed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    /// True if the tool executed successfully, false otherwise.
    pub success: bool,
    /// The output string or result of the tool execution.
    pub output: String,
    /// An optional error message if the execution was blocked or failed.
    pub error: Option<String>,
    /// The cryptographic receipt generated for this execution.
    pub receipt: Option<CryptographicReceipt>,
}

/// The core trait defining a tool available to the AI agent.
pub trait Tool: Send + Sync {
    /// Returns the unique name of the tool.
    fn name(&self) -> &str;

    /// Returns the description of what the tool does.
    fn description(&self) -> &str;

    /// Returns the JSON schema representing the tool's parameters.
    fn parameters_schema(&self) -> serde_json::Value;

    /// Executes the tool with the provided arguments and security context.
    ///
    /// The runtime guarantees that `args` validates against `parameters_schema`.
    /// Execution must be "fail-closed" by default.
    fn execute(&self, args: serde_json::Value, ctx: &ToolContext) -> ToolResult;
}

/// Defines a durable memory backend to log executions and audit trails.
pub trait Memory: Send + Sync {
    /// Logs a tool execution into durable storage.
    fn log_tool_execution(
        &self,
        tool_name: &str,
        args: &serde_json::Value,
        result: &ToolResult,
    ) -> Result<(), String>;

    /// Retrieves the audit trail of tool executions.
    /// In a real implementation this might support pagination or filtering.
    fn get_audit_trail(&self) -> Result<Vec<(String, String, ToolResult)>, String>;
}

/// A structured tool call generated by a Provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub tool_name: String,
    pub args: serde_json::Value,
}

/// The core trait defining an LLM Provider.
pub trait Provider: Send + Sync {
    /// Generates a tool call based on a natural language prompt and available tools.
    fn generate_tool_call(
        &self,
        prompt: &str,
        available_tools: &[(&str, serde_json::Value)],
    ) -> Result<Option<ToolCall>, String>;
}
